### ISSUE TITLE
Conflicts with node-red-contrib-postgres

### ISSUE THREAD

**Issue by Digicrat** [arkancrow/node-red-contrib-postgres-listen#1]
Installing both modules results in this module not working, and requiring some manual edits to resolve.  See https://github.com/node-red/node-red/issues/1836

The "postgresdb' module is redefined in this node identically to that in node-red-contrib-postgres.  I suggest completely removing it from this node, and instead define node-red-contrib-postgres as a dependency.  Renaming it would also work, but be less useful for those planning on using both modules -- for reliability it's often best to query the DB to confirm details after receiving a notification.

**Comment by arkancrow** [comment]
@Digicrat I removed the postgresdb module. [https://flows.nodered.org/node/node-red-contrib-postgres](url) is now a dependency as you suggested.
