### ISSUE TITLE
Incompatible with latest node-red version

### ISSUE THREAD

**Issue by gar-syn** [arkancrow/node-red-contrib-postgres-listen#2]
Incompatible with latest version of node-red. I think this is due to compatibility issues with the postgres plugin.

Error as such - 

```
14 May 07:36:03 - [info] Waiting for missing types to be registered:
14 May 07:36:03 - [info]  - postgresdb
14 May 07:36:03 - [info]  - postgres
```

**Comment by gar-syn** [comment]
Fixed by changing the dependency to the updated postgres package (https://www.npmjs.com/package/node-red-contrib-re-postgres)

`{
  "name": "node-red-contrib-postgres-listen",
  "version": "0.3.0",
  "description": "A Node-RED node to listen to pg_notify",
  "dependencies": {
    "node-red-contrib-re-postgres": "~0.1.9",
    "pg": "^6.1.5"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/arkancrow/node-red-contrib-postgres-listen"
  },
  "license": "Apache-2.0",
  "keywords": [
    "node-red",
    "postgres",
    "postgresql",
    "pg_notify"
  ],
  "node-red": {
    "nodes": {
      "PostgreSQLListen": "pglisten.js"
    }
  },
  "author": {
    "name": "Vincent Schoonenburg",
    "email": "arkancrow@gmail.com"
  }
}`

**Comment by gar-syn** [comment]
Pull request:

https://github.com/arkancrow/node-red-contrib-postgres-listen/pull/3

**Comment by arkancrow** [comment]
Pull request merged.

Thanks for the fix.
